In [21]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split, KFold
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import matplotlib
from matplotlib import pyplot as plt
# import seaborn as sns
%matplotlib inline

In [22]:
data_all = pd.read_csv("./data/meilleursjeuvideo.csv")

In [23]:
data_all.describe()

,Jeux,Description,Sortie,Test,Avis
count,200,197,200,200,187
unique,200,197,172,3,41
top,Umineko no Naku Koro ni : Shinjitsu to Gensô n...,Gears of War 3 est un jeu d'action sur Xbox 36...,1993,19/20,18.7/20
freq,1,1,6,123,14

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test = train_test_split(data_all)

In [26]:
X_train.describe()

,Jeux,Description,Sortie,Test,Avis
count,150,148,150,150,139
unique,150,148,134,3,37
top,Driver,Gears of War 3 est un jeu d'action sur Xbox 36...,1993,19/20,18.7/20
freq,1,1,4,91,12

In [27]:
X_test.describe()

,Jeux,Description,Sortie,Test,Avis
count,50,49,50,50,48
unique,50,49,46,3,27
top,Umineko no Naku Koro ni : Shinjitsu to Gensô n...,"Tiré de la série des Final Fantasy, Theathrhyt...",1994,19/20,18.3/20
freq,1,1,3,32,4

In [28]:
X_train.head()

,Jeux,Description,Sortie,Test,Avis
139,Castlevania : Order of Ecclesia sur DS,Dracula refait surface alors que le clan Belmo...,27 novembre 2008,18/20,NaN
192,Dungeon Keeper 2 sur PC,Dungeon Keeper 2 est un jeu de stratégie sorti...,Juillet 1999,18/20,18/20
175,Divinity : Original Sin,"Jeu de rôle au tour par tour, Divinity : Origi...",30 juin 2014,18/20,16.8/20
187,Virtua Fighter 4 Evolution,Virtua Fighter 4 Evolution est un jeu de comba...,20 juin 2003,18/20,16.4/20
5,Kingpin : Life of Crime sur PC,Kingpin : Life of Crime est un jeu de tir à la...,Août 1999,19/20,17.5/20

In [69]:
[X_train['Test'].str.split('/')[i] for i in range(len(X_train))]

KeyError: 1

In [36]:
X_train.head()

,Jeux,Description,Sortie,Test,Avis
139,Castlevania : Order of Ecclesia sur DS,Dracula refait surface alors que le clan Belmo...,27 novembre 2008,18/20,NaN
192,Dungeon Keeper 2 sur PC,Dungeon Keeper 2 est un jeu de stratégie sorti...,Juillet 1999,18/20,18/20
175,Divinity : Original Sin,"Jeu de rôle au tour par tour, Divinity : Origi...",30 juin 2014,18/20,16.8/20
187,Virtua Fighter 4 Evolution,Virtua Fighter 4 Evolution est un jeu de comba...,20 juin 2003,18/20,16.4/20
5,Kingpin : Life of Crime sur PC,Kingpin : Life of Crime est un jeu de tir à la...,Août 1999,19/20,17.5/20