In [1]:
import pandas as pd
import re

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MinMaxScaler

pd.options.display.max_columns = None

train = pd.read_csv("../datasources/houseprices/train.csv")
test = pd.read_csv("../datasources/houseprices/test.csv")
full = pd.concat([train, test]) # Assemble les deux jeux de données

Informations statistiques (sur les variables numériques)

In [2]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1379.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,567.240411,1057.429452,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,6.517808,0.613014,1978.506164,1.767123,472.980137,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,441.866955,438.705324,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,1.625393,0.644666,24.689725,0.747315,213.804841,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,223.000000,795.750000,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1961.000000,1.000000,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,477.500000,991.500000,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1980.000000,2.000000,480.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,808.000000,1298.250000,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,2010.000000,4.000000,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

Nombre de lignes / colonnes

In [3]:
train.shape

(1460, 81)

Informations / colonnes (type et NaN)

In [41]:
train.info(verbose=True,null_counts =True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [38]:
train.get_dtype_counts()

float64     3
int64      35
object     43
dtype: int64

In [72]:
print("Nombre de colonnes: " + str(train.columns.shape[0]))
print("Nombre de lignes: " + str(train.shape[0]))
print("Affichage des colonnes ayant des données NaN:")
for col in train.columns:
    nanCount = train[col].isnull().sum()
    if (nanCount > 0):
        print("   * " + col + "> " + str(nanCount) + " (" + str(round(nanCount / train.shape[0] * 100, 2)) + " %)")
print("Affichage des colonnes Non numériques:")
for col in train.columns:
    myType = str(train[col].dtype)
    if (myType[:3] != "int" and myType[:5] != "float"):
        print("   * " + col + "> " + myType)

Nombre de colonnes: 81
Nombre de lignes: 1460
Affichage des colonnes ayant des données NaN:
   * LotFrontage> 259 (17.74 %)
   * Alley> 1369 (93.77 %)
   * MasVnrType> 8 (0.55 %)
   * MasVnrArea> 8 (0.55 %)
   * BsmtQual> 37 (2.53 %)
   * BsmtCond> 37 (2.53 %)
   * BsmtExposure> 38 (2.6 %)
   * BsmtFinType1> 37 (2.53 %)
   * BsmtFinType2> 38 (2.6 %)
   * Electrical> 1 (0.07 %)
   * FireplaceQu> 690 (47.26 %)
   * GarageType> 81 (5.55 %)
   * GarageYrBlt> 81 (5.55 %)
   * GarageFinish> 81 (5.55 %)
   * GarageQual> 81 (5.55 %)
   * GarageCond> 81 (5.55 %)
   * PoolQC> 1453 (99.52 %)
   * Fence> 1179 (80.75 %)
   * MiscFeature> 1406 (96.3 %)
Affichage des colonnes Non numériques:
   * MSZoning> object
   * Street> object
   * Alley> object
   * LotShape> object
   * LandContour> object
   * Utilities> object
   * LotConfig> object
   * LandSlope> object
   * Neighborhood> object
   * Condition1> object
   * Condition2> object
   * BldgType> object
   * HouseStyle> object
   * RoofStyle> object
   * RoofMatl> object
   * Exterior1st> object
   * Exterior2nd> object
   * MasVnrType> object
   * ExterQual> object
   * ExterCond> object
   * Foundation> object
   * BsmtQual> object
   * BsmtCond> object
   * BsmtExposure> object
   * BsmtFinType1> object
   * BsmtFinType2> object
   * Heating> object
   * HeatingQC> object
   * CentralAir> object
   * Electrical> object
   * KitchenQual> object
   * Functional> object
   * FireplaceQu> object
   * GarageType> object
   * GarageFinish> object
   * GarageQual> object
   * GarageCond> object
   * PavedDrive> object
   * PoolQC> object
   * Fence> object
   * MiscFeature> object
   * SaleType> object
   * SaleCondition> object

In [91]:
for col in train.columns:
    print("   * " + col + "\n")
    print(str(train[col].value_counts(sort=True).head(5)) + "\n")

   * Id

1460    1
479     1
481     1
482     1
483     1
Name: Id, dtype: int64

   * MSSubClass

20     536
60     299
50     144
120     87
30      69
Name: MSSubClass, dtype: int64

   * MSZoning

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

   * LotFrontage

60.0    143
70.0     70
80.0     69
50.0     57
75.0     53
Name: LotFrontage, dtype: int64

   * LotArea

7200     25
9600     24
6000     17
10800    14
9000     14
Name: LotArea, dtype: int64

   * Street

Pave    1454
Grvl       6
Name: Street, dtype: int64

   * Alley

Grvl    50
Pave    41
Name: Alley, dtype: int64

   * LotShape

Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

   * LandContour

Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

   * Utilities

AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

   * LotConfig

Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

   * LandSlope

Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

   * Neighborhood

NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Name: Neighborhood, dtype: int64

   * Condition1

Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
Name: Condition1, dtype: int64

   * Condition2

Norm      1445
Feedr        6
PosN         2
Artery       2
RRNn         2
Name: Condition2, dtype: int64

   * BldgType

1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

   * HouseStyle

1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
Name: HouseStyle, dtype: int64

   * OverallQual

5    397
6    374
7    319
8    168
4    116
Name: OverallQual, dtype: int64

   * OverallCond

5    821
6    252
7    205
8     72
4     57
Name: OverallCond, dtype: int64

   * YearBuilt

2006    67
2005    64
2004    54
2007    49
2003    45
Name: YearBuilt, dtype: int64

   * YearRemodAdd

1950    178
2006     97
2007     76
2005     73
2004     62
Name: YearRemodAdd, dtype: int64

   * RoofStyle

Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Name: RoofStyle, dtype: int64

   * RoofMatl

CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Membran       1
Name: RoofMatl, dtype: int64

   * Exterior1st

VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
Name: Exterior1st, dtype: int64

   * Exterior2nd

VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
Name: Exterior2nd, dtype: int64

   * MasVnrType

None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

   * MasVnrArea

0.0      861
72.0       8
180.0      8
108.0      8
120.0      7
Name: MasVnrArea, dtype: int64

   * ExterQual

TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

   * ExterCond

TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

   * Foundation

PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Name: Foundation, dtype: int64

   * BsmtQual

TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

   * BsmtCond

TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

   * BsmtExposure

No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

   * BsmtFinType1

Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
Name: BsmtFinType1, dtype: int64

   * BsmtFinSF1

0      467
24      12
16       9
20       5
686      5
Name: BsmtFinSF1, dtype: int64

   * BsmtFinType2

Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
Name: BsmtFinType2, dtype: int64

   * BsmtFinSF2

0      1293
180       5
374       3
551       2
93        2
Name: BsmtFinSF2, dtype: int64

   * BsmtUnfSF

0      118
728      9
384      8
572      7
600      7
Name: BsmtUnfSF, dtype: int64

   * TotalBsmtSF

0       37
864     35
672     17
912     15
1040    14
Name: TotalBsmtSF, dtype: int64

   * Heating

GasA    1428
GasW      18
Grav       7
Wall       4
OthW       2
Name: Heating, dtype: int64

   * HeatingQC

Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64

   * CentralAir

Y    1365
N      95
Name: CentralAir, dtype: int64

   * Electrical

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

   * 1stFlrSF

864     25
1040    16
912     14
848     12
894     12
Name: 1stFlrSF, dtype: int64

   * 2ndFlrSF

0      829
728     10
504      9
672      8
546      8
Name: 2ndFlrSF, dtype: int64

   * LowQualFinSF

0      1434
80        3
360       2
528       1
53        1
Name: LowQualFinSF, dtype: int64

   * GrLivArea

864     22
1040    14
894     11
848     10
1456    10
Name: GrLivArea, dtype: int64

   * BsmtFullBath

0    856
1    588
2     15
3      1
Name: BsmtFullBath, dtype: int64

   * BsmtHalfBath

0    1378
1      80
2       2
Name: BsmtHalfBath, dtype: int64

   * FullBath

2    768
1    650
3     33
0      9
Name: FullBath, dtype: int64

   * HalfBath

0    913
1    535
2     12
Name: HalfBath, dtype: int64

   * BedroomAbvGr

3    804
2    358
4    213
1     50
5     21
Name: BedroomAbvGr, dtype: int64

   * KitchenAbvGr

1    1392
2      65
3       2
0       1
Name: KitchenAbvGr, dtype: int64

   * KitchenQual

TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

   * TotRmsAbvGrd

6    402
7    329
5    275
8    187
4     97
Name: TotRmsAbvGrd, dtype: int64

   * Functional

Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Name: Functional, dtype: int64

   * Fireplaces

0    690
1    650
2    115
3      5
Name: Fireplaces, dtype: int64

   * FireplaceQu

Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64

   * GarageType

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
Name: GarageType, dtype: int64

   * GarageYrBlt

2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
Name: GarageYrBlt, dtype: int64

   * GarageFinish

Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

   * GarageCars

2    824
1    369
3    181
0     81
4      5
Name: GarageCars, dtype: int64

   * GarageArea

0      81
440    49
576    47
240    38
484    34
Name: GarageArea, dtype: int64

   * GarageQual

TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

   * GarageCond

TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

   * PavedDrive

Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64

   * WoodDeckSF

0      761
192     38
100     36
144     33
120     31
Name: WoodDeckSF, dtype: int64

   * OpenPorchSF

0     656
36     29
48     22
20     21
40     19
Name: OpenPorchSF, dtype: int64

   * EnclosedPorch

0      1252
112      15
96        6
120       5
144       5
Name: EnclosedPorch, dtype: int64

   * 3SsnPorch

0      1436
168       3
216       2
144       2
180       2
Name: 3SsnPorch, dtype: int64

   * ScreenPorch

0      1344
192       6
224       5
120       5
189       4
Name: ScreenPorch, dtype: int64

   * PoolArea

0      1453
738       1
648       1
576       1
555       1
Name: PoolArea, dtype: int64

   * PoolQC

Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

   * Fence

MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

   * MiscFeature

Shed    49
Othr     2
Gar2     2
TenC     1
Name: MiscFeature, dtype: int64

   * MiscVal

0      1408
400      11
500       8
700       5
450       4
Name: MiscVal, dtype: int64

   * MoSold

6    253
7    234
5    204
4    141
8    122
Name: MoSold, dtype: int64

   * YrSold

2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64

   * SaleType

WD       1267
New       122
COD        43
ConLD       9
ConLI       5
Name: SaleType, dtype: int64

   * SaleCondition

Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
Name: SaleCondition, dtype: int64

   * SalePrice

140000    20
135000    17
145000    14
155000    14
190000    13
Name: SalePrice, dtype: int64

In [86]:
print('col> ' + str(train['SaleCondition'].value_counts().head(10)))

col> Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64